---
- name: Install basic required software
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - python3-docker
      - gnupg-agent

- name: Add docker gpg apt key
  ansible.builtin.shell:
    cmd: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/docker.gpg > /dev/null'


- name: Get architecture
  ansible.builtin.shell: dpkg --print-architecture
  register: deb_architecture

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/trusted.gpg.d/docker.gpg] \
          https://download.docker.com/linux/{{ ansible_distribution | lower }} \
          {{ ansible_distribution_release | lower }} stable"
    state: present

- name: Install basic required software
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Create docker config directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Create docker data directory
  ansible.builtin.file:
    path: "{{ docker_data_root }}"
    state: directory
    mode: '0755'

- name: Copy docker config file
  ansible.builtin.template:
    src: daemon.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart docker

- name: Install docker-ce package
  ansible.builtin.apt:
    name: docker-ce
    state: present
